### ISSUE TITLE
add support for multiple terminals using tabs

### ISSUE THREAD

**Issue by RafalSkolasinski** [lbonn/i3-quickterm#16]
Guake, Yakukake (or even Konsole) allow you to have multiple terminals simultaneously and have them under different tabs.

I wonder if it would be possible to extend your code to somehow support this in a neat way?

**Comment by tonydero** [comment]
Just to make sure you (any anyone else that might look at this) knows of other options, one can use tmux to add tabs to any terminal emulator.

**Comment by RafalSkolasinski** [comment]
I know about tmux but I really hate how copy - paste of mouse highlighted text works in it

**Comment by tonydero** [comment]
I figured you knew and had your reasons, but wanted to make sure!

**Comment by neurolabs** [comment]
I use a terminal emulator that provides this feature (konsole, the supported gnome-terminal also does provide tabs) and would not need it in this project.

**Comment by markstos** [comment]
@RafalSkolasinski This is already supported. With the quickterm focused, use a sequence of  commands through key bindings that you probably already have:
  *  `split horizontal`
  * `layout tabbed`
  * Whatever you launch with the quickterm focused will now appear in a tab. 
  
Now when you use the keybinding to toggle the quickterm, you will be toggling an i3/Sway tabbed container.  This has been tested on Sway.

**Comment by lbonn** [comment]
I'll close this as this can be solved with native i3/sway as explained above.
