### ISSUE TITLE
quickterm does not take full width

### ISSUE THREAD

**Issue by piotrekfus91** [lbonn/i3-quickterm#19]
OS: Manjaro 20.2
i3: 4.19
Laptop: Dell XPS 7590
Screen resolution: 3840x2160

When I start quickterm it does not take full length of the screen, it takes about 70%. My config goes as follows:
```
{
    "term": "alacritty",
    "history": "{$HOME}/.cache/i3/i3-quickterm.order",
    "ratio": 0.25,
    "pos": "top",
    "shells": {
        "shell": "{$SHELL}"
    }
}
```

Any hints?

**Comment by ram02z** [comment]
@piotrekfus91 in your i3 config, remove the `floating_maximum_size` property if you have it as it will constrain the window width.

**Comment by markstos** [comment]
@piotrekfus91 Try launching Alacritty as a floating window. Is the same height as you experience with `i3-quickterm`?

The height is probably being set by by `window.dimensions.lines` in `alacritty.yml`. If you want a different height of window for `i3-quickterm` usage, call it as `alacritty --option  window.dimensions.lines=80` and see if you get a result like you want. 

If so, this issue can be closed-- it's not an `i3-quickterm` bug.

**Comment by markstos** [comment]
@piotrekfus91 Your title doesn't agree with your description. The title says "full width", while the description says "full length". Are you refering to the horizontal or vertical dimension?

**Comment by piotrekfus91** [comment]
@ram02z thanks, it helped. Unfortunatelly I would prefer to have `floating_maximum_size` left as-is, but I didn't find any option to set it only for specific window. Still, it is a problem in i3, not in quickterm, so thanks for your answer!
@markstos When I launch Alacritty as a floating window it has different size (it is small actually ;) ).
You are right - I meant width of course (I'm polish, so sorry, length is for me obvious but it might be a false-friend, vertical size I would call height).
Thanks guys!
