### ISSUE TITLE
Can't use, getting errors

### ISSUE THREAD

**Issue by qazip** [lbonn/i3-quickterm#4]
```
Traceback (most recent call last):
  File "i3-quickterm", line 250, in <module>
    toggle_quickterm_select(conf)
  File "i3-quickterm", line 194, in toggle_quickterm_select
    toggle_quickterm(conf, shell)
  File "i3-quickterm", line 219, in toggle_quickterm
    os.execvp(term_cmd[0], term_cmd)
  File "/usr/lib/python3.5/os.py", line 615, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.5/os.py", line 660, in _execvpe
    raise last_exc.with_traceback(tb)
  File "/usr/lib/python3.5/os.py", line 650, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
```

What seems to be the problem here? Am I doing something wrong? I'm using i3 4.15 on ubuntu 16.04.

**Comment by qazip** [comment]
I managed to fix those errors, and it works when I run it from terminal but I can't make it hide/un-hide or make it work from shortcuts.

What am I doing wrong? This is what I have in ~/.config/i3/config:

`bindsym $mod+t exec i3-quickterm`

Both the i3-quickterm and i3-quickterm.json are in the same folder (~/.config/i3/)..

EDIT: Solved. Full path works.

**Comment by lbonn** [comment]
Good that you resolved your issue.
From your description it sounds like a PATH inconsistency issue: PATH modified in your shell's config (e.g: `.bashrc`) which would be sourced in your shell and not when i3 was run.

It's usually best to set these variables in `.profile`, `.xprofile` or similar, depending on how  X is launched.
